travis:
  secure:
    BINSTAR_TOKEN: W2kaqbYMkwbmgw2Q6im4HW55Yu1M5FabKoQ10R4Dj6UJUw5N5KSF+e+TAswhcaCBJSjfHf91aXfBjzRteHjZxE3gCOBfdFJC1AHKT6dC1tdCCewVKojPJYMkiDBNCZuFIUARBFQ+Ar+e5y8fxVZiUASM4j4MScx1z3ra8Eyh7RLVy2qa+4dlzWSkQopPbJRPJEtAwwgnJGLtZhCDU1AjDRK2A/KMPqBaNa58yrQNWBQ/zOAMnY+H8ufX6Cq/lIt9Sc9FnE06QLcGzbBck/uI54rwEl5lojxTzD0QWuFcKzftgalbPaGaM2uH3nHW973DqYLx2lzbcG7lCmPWpyVFoox5eGNs5dzKJ2gWyFixYpZIzQevZoDhKkl7omvCclCkDDVrIPFV7nXvw2CV5+IjH08XWU4bfYmOC70VYct1ek0uZVLXOxs1fHmftMTr1lO67kSUXh9NJHuFRTx4aBsE5K2BLhXncSvbfycInr22xQtOAY+w27ePS2HhebdxiRr3hAkJ3FKqC8n1NGogjjkK9Z+7YM+FjAy6jvNa+7RdhyvpOmCXMEMQ4U7JARapnQyfJvxOFG9fculT5o0t4GmUzZu6GHJhQchrRj1WZvoEUfKKr7NIm6gXK7XO3152NW/AKc9/liKdN776mhSZ47sudN3ifM30gieeyfUNPa2LakU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
