travis:
  secure:
    BINSTAR_TOKEN: pm4yOYSqWdzCXDqTkAwX1g+MAzJ/64875n8zb1Rob2qf3R8tnRHrq+5VUprLY93FdfSzM2Y1rGSMVE226RTm+jL0O8EkfmEWi8/RPAVw+7EnWucWfdGQMwG8kvt0u5wPYGnX6zW1hjenOpvrTWmYcIobP7dSuDFlnSHaDwwkpiyUzXoc1K3e13pCEe55mMidAp6vq3CO+z0LZasC/EnjzXytswRhxL2fnxRBMYaeD10FsLxLEv0I2JC/u45yEP7YzT7+9MhCgv2sb9Ppri97lt9JLO1koYesti6QFvuOBh0Nn1FXH0xpO+SnMGGwGllr2VrXubsY4vswxol9ZLhGLP16ZVqoED5G2pFfBXjWWJ6FWiqCLXTLqPwRPUwWPUhPTfpGgrUmzd7HRT+S+o0T3SxrL+2ygGIfyDn4uN8nOtOL2aYc2cBu4tPKZw00BL5C67nNyfGpVpM5mmNb4pMtp1GU9i6dDrfUtdvqpm1zVaF2FBbprT9SHQXamN6XTaYOfRDJ5MtxK8mbtdh2mYpW3qhnRvzedCyjKTJoVBQEbZDdQcm21grONktF7d9FJq9KKkU/3loCRnKV/jtKQfToWkwP2TFZxjLXN8REaCLJtFcy39KdB3baXcFVk7W3cxJAw5vyQbdlrImlUP7e9jT4QffzyvhjYRTK57+mlj4qTJE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
